words_list = ['apple', 'banana', 'orange', 'grape', 'strawberry', 'kiwi', 'pineapple', 'mango', 'watermelon', 'peach',
          'pear', 'cherry', 'blueberry', 'raspberry', 'lemon', 'lime', 'plum', 'apricot', 'fig', 'pomegranate',
          'nectarine', 'coconut', 'avocado', 'guava', 'passion fruit', 'dragon fruit', 'lychee', 'persimmon', 'papaya',
          'dog', 'cat', 'horse', 'rabbit', 'hamster', 'guinea pig', 'ferret', 'gerbil', 'mouse', 'rat',
          'parrot', 'canary', 'finch', 'budgerigar', 'cockatiel', 'lovebird', 'macaw', 'cockatoo', 'african grey', 'amazon',
          'goldfish', 'betta fish', 'guppy', 'koi', 'tetra', 'swordtail', 'molly', 'platy', 'angel fish', 'discus',
          'turtle', 'tortoise', 'gecko', 'iguana', 'chameleon', 'skink', 'anole', 'bearded dragon', 'snake', 'python',
          'frog', 'toad', 'newt', 'salamander', 'axolotl', 'tadpole', 'hermit crab', 'scorpion', 'tarantula', 'millipede',
          'centipede', 'beetle', 'ant', 'grasshopper', 'cricket', 'caterpillar', 'butterfly', 'moth', 'bee', 'wasp',
          'spider', 'fly', 'mosquito', 'ladybug', 'firefly', 'dragonfly', 'beetle', 'crab', 'lobster', 'shrimp', 'prawn']
